### ISSUE TITLE
rar archives ignored when adding a folder in library

### ISSUE THREAD

**Issue by ghost** [multiSnow/mcomix3#90]
You add a folder in the library containing various archives. The ".rar" archives are not added. All the rest are probably ok.

Just add "mcomix3/test/files/archives" in the library.

**Comment by multiSnow** [comment]
Sorry, I could not reproduce it. A clear instance in portable mode does recognize all archives including rar files.
Similar issue is also reported in https://sourceforge.net/p/mcomix/bugs/115/ , and should be fixed by https://github.com/multiSnow/mcomix3/commit/605e06a87f288baba34fd90c1c117d5aae94d3d2 and https://github.com/multiSnow/mcomix3/commit/391d9808a51a63ab6fad31a463ec463ac973be17 .
If rar file is still not recognized, it maybe caused by `last filter in library filechooser` preference key. Please set it to `0` in `preferences.conf` and retry.

**Comment by ghost** [comment]
when adding a folder with archives, rar archives are not added. cbr archives are properly added. If you select one rar file, it's added properly.

last filter is 0
problem persist with a new config/mcomix folder.

i have unrar installed, not rar.
